version: "3.9"

services:
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - 5432:5432
