version: "3.9"

services:
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./server:/server
      - ./frontend:/frontend
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
