version: "3.9"

services:
  server:
    build: .
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; cd /app/server; yarn dev'
    #production command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; nodemon /app/server/bin/www'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DB}
    ports:
      - 5432:5432
  postgres_gui:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 80:80
    links:
      - postgres
    depends_on:
      - postgres

